export default {
  login: "richardestes",
  id: 35784400,
  node_id: "MDQ6VXNlcjM1Nzg0NDAw",
  avatar_url: "https://avatars.githubusercontent.com/u/35784400?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/richardestes",
  html_url: "https://github.com/richardestes",
  followers_url: "https://api.github.com/users/richardestes/followers",
  following_url: "https://api.github.com/users/richardestes/following{/other_user}",
  gists_url: "https://api.github.com/users/richardestes/gists{/gist_id}",
  starred_url: "https://api.github.com/users/richardestes/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/richardestes/subscriptions",
  organizations_url: "https://api.github.com/users/richardestes/orgs",
  repos_url: "https://api.github.com/users/richardestes/repos",
  events_url: "https://api.github.com/users/richardestes/events{/privacy}",
  received_events_url: "https://api.github.com/users/richardestes/received_events",
  type: "User",
  site_admin: false,
  name: "Richard Estes",
  company: null,
  blog: "richard.estes",
  location: "Orange County, California",
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 4,
  following: 8,
  created_at: "2018-01-24T22:42:01Z",
  updated_at: "2021-02-18T23:01:28Z",
};
