export default [
  {
    "login": "j00022",
    "id": 44303050,
    "node_id": "MDQ6VXNlcjQ0MzAzMDUw",
    "avatar_url": "https://avatars.githubusercontent.com/u/44303050?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/j00022",
    "html_url": "https://github.com/j00022",
    "followers_url": "https://api.github.com/users/j00022/followers",
    "following_url": "https://api.github.com/users/j00022/following{/other_user}",
    "gists_url": "https://api.github.com/users/j00022/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/j00022/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/j00022/subscriptions",
    "organizations_url": "https://api.github.com/users/j00022/orgs",
    "repos_url": "https://api.github.com/users/j00022/repos",
    "events_url": "https://api.github.com/users/j00022/events{/privacy}",
    "received_events_url": "https://api.github.com/users/j00022/received_events",
    "type": "User",
    "site_admin": false,
  },
  {
    "login": "BrianDeJesus",
    "id": 14815045,
    "node_id": "MDQ6VXNlcjE0ODE1MDQ1",
    "avatar_url": "https://avatars.githubusercontent.com/u/14815045?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/BrianDeJesus",
    "html_url": "https://github.com/BrianDeJesus",
    "followers_url": "https://api.github.com/users/BrianDeJesus/followers",
    "following_url": "https://api.github.com/users/BrianDeJesus/following{/other_user}",
    "gists_url": "https://api.github.com/users/BrianDeJesus/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/BrianDeJesus/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/BrianDeJesus/subscriptions",
    "organizations_url": "https://api.github.com/users/BrianDeJesus/orgs",
    "repos_url": "https://api.github.com/users/BrianDeJesus/repos",
    "events_url": "https://api.github.com/users/BrianDeJesus/events{/privacy}",
    "received_events_url": "https://api.github.com/users/BrianDeJesus/received_events",
    "type": "User",
    "site_admin": false,
  },
  {
    "login": "peterdmendez",
    "id": 4584725,
    "node_id": "MDQ6VXNlcjQ1ODQ3MjU=",
    "avatar_url": "https://avatars.githubusercontent.com/u/4584725?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/peterdmendez",
    "html_url": "https://github.com/peterdmendez",
    "followers_url": "https://api.github.com/users/peterdmendez/followers",
    "following_url": "https://api.github.com/users/peterdmendez/following{/other_user}",
    "gists_url": "https://api.github.com/users/peterdmendez/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/peterdmendez/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/peterdmendez/subscriptions",
    "organizations_url": "https://api.github.com/users/peterdmendez/orgs",
    "repos_url": "https://api.github.com/users/peterdmendez/repos",
    "events_url": "https://api.github.com/users/peterdmendez/events{/privacy}",
    "received_events_url": "https://api.github.com/users/peterdmendez/received_events",
    "type": "User",
    "site_admin": false,
  },
  {
    "login": "PathToSharePoint",
    "id": 40323257,
    "node_id": "MDQ6VXNlcjQwMzIzMjU3",
    "avatar_url": "https://avatars.githubusercontent.com/u/40323257?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/PathToSharePoint",
    "html_url": "https://github.com/PathToSharePoint",
    "followers_url": "https://api.github.com/users/PathToSharePoint/followers",
    "following_url": "https://api.github.com/users/PathToSharePoint/following{/other_user}",
    "gists_url": "https://api.github.com/users/PathToSharePoint/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/PathToSharePoint/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/PathToSharePoint/subscriptions",
    "organizations_url": "https://api.github.com/users/PathToSharePoint/orgs",
    "repos_url": "https://api.github.com/users/PathToSharePoint/repos",
    "events_url": "https://api.github.com/users/PathToSharePoint/events{/privacy}",
    "received_events_url": "https://api.github.com/users/PathToSharePoint/received_events",
    "type": "User",
    "site_admin": false,
  },
];
